# networks:
#   n8n-network:
#     external: true

# tạo network tự động (local test)
networks:
  n8n-network:
    driver: bridge

volumes:
  db_storage:
  n8n_storage:
  redis_storage:

x-shared: &shared
  restart: always
  environment:
    # Database
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}          # n8n
    - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}   # n8n
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    - DB_POSTGRESDB_SCHEMA=public

    # Queue
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_HOST=redis
    - QUEUE_HEALTH_CHECK_ACTIVE=true

    # Core
    - N8N_BASIC_AUTH_ACTIVE=false
    # - N8N_PROTOCOL=https
    - N8N_PORT=8443
    - N8N_PROTOCOL=http # (local dev)
    # - N8N_PORT=5678 # (local dev)
    - VUE_APP_URL_BASE_API=https://${N8N_HOST}
    - WEBHOOK_TUNNEL_URL=https://${N8N_HOST}
    - WEBHOOK_URL=https://${N8N_HOST}
    - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    - N8N_SECURE_COOKIE=false
    - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    - N8N_TRUST_PROXY=1

    # Disable unused features
    - N8N_AI_ENABLED=false
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false

    # Recommended for v2 (safe)
    - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
    - N8N_VERSION_NOTIFICATIONS_ENABLED=false
    - N8N_RELEASE_NOTIFICATIONS_ENABLED=false

    # Timezone
    - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh

  links:
    - postgres
    - redis

  volumes:
    - n8n_storage:/home/node/
    - ./certs:/home/certs/

  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

  networks:
    - n8n-network

services:
  postgres:
    image: postgres:11
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - n8n-network

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always
    volumes:
      - redis_storage:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - n8n-network

  n8n:
    <<: *shared
    hostname: n8n
    container_name: n8n
    image: n8nio/n8n:2.3.0
    command: ["start"]
    ports:
      - "8443:8443"
      # - "5678:5678" # (local dev)

  n8n-worker:
    <<: *shared
    container_name: n8n_worker
    image: n8nio/n8n:2.3.0
    command: ["worker"]
    depends_on:
      - n8n
